version: '3.9'

services:  
  chat_history_saver:
      build: 
        context: ./backend
        dockerfile: ChatConsumersDockerfile 
      container_name: chatConsumer
      environment:
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
        - RabbitMqConfig__Username=chatConsumer
        - RabbitMqConfig__Password=Passw0rd
        - RabbitMqConfig__Hostname=rabbitmq
        - RabbitMqConfig__Port=5672
      depends_on:
       - rabbitmq
        
  backend:
      build: 
        context: ./backend
        dockerfile: CarsharingDockerfile
      container_name: backend
      environment:
        - FrontendHost__Main = ${FRONT__MAIN}
        - FrontendHost__Admin = ${FRONT__ADMIN}
        - ASPNETCORE_ENVIRONMENT=${BACK_ASP_ENV}
        - ASPNETCORE_URLS=${ASPNETCORE_URLS}
        - ASPNETCORE_HTTPS_PORT=${ASPNETCORE_HTTPS_PORT}
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
        - Authorization__Google__AppId = ${GOOGLE_APP_ID}
        - Authorization__Google__AppSecret = ${GOOGLE_APP_SECRET}
        - RabbitMqConfig__Username=chatConsumer
        - RabbitMqConfig__Password=Passw0rd
        - RabbitMqConfig__Hostname=rabbitmq
        - RabbitMqConfig__Port=5672
      depends_on:
       - db 
       - rabbitmq   
      ports:
        - ${BACK_ASP_PORTS}
        - ${BACK_ASP_PORTS2}
      volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        
  website:
      build: ./frontend/website
      container_name: frontend
      
      ports:
        - ${FRONT_WEBSITE_PORTS}
        
  admin:
      build: ./frontend/admin
      container_name: admin_dashboard
      ports:
        - ${FRONT_ADMIN_PORTS}
  db:
      container_name: database
      image: postgres:latest
      environment:
        POSTGRES_DB: Carsharing
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ../2. Init Database:/docker-entrypoint-initdb.d
      ports:
        - ${DB_PORTS}
        
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "chatConsumer"
      RABBITMQ_DEFAULT_PASS: "Passw0rd"
