version: '3.9'

services:  
  chat_history_saver:
      build: 
        context: ./backend
        dockerfile: ChatConsumersDockerfile 
      container_name: chatConsumer
      environment:
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
        - RabbitMqConfig__Username=chatConsumer
        - RabbitMqConfig__Password=P@ssw0rd
        - RabbitMqConfig__Hostname=RabbitMq
        - RabbitMqConfig__Port=5672
      depends_on:
       - rabbitmq
        
  backend:
      build: 
        context: ./backend
        dockerfile: CarsharingDockerfile
      container_name: backend
      environment:
        - FrontendHost__Main = ${FRONT__MAIN}
        - FrontendHost__Admin = ${FRONT__ADMIN}
        - ASPNETCORE_ENVIRONMENT=${BACK_ASP_ENV}
        - Authorization__Google__AppId = ${GOOGLE_APP_ID}
        - Authorization__Google__AppSecret = ${GOOGLE_APP_SECRET}
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      depends_on:
       - db 
       - rabbitmq   
      ports:
        - ${BACK_ASP_PORTS}
        
  website:
      build: ./frontend/website
      container_name: frontend
      
      ports:
        - ${FRONT_WEBSITE_PORTS}
        
  admin:
      build: ./frontend/admin
      container_name: admin_dashboard
      ports:
        - ${FRONT_ADMIN_PORTS}
  db:
      container_name: database
      image: postgres:latest
      environment:
        POSTGRES_DB: Carsharing
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ../2. Init Database:/docker-entrypoint-initdb.d
      ports:
        - ${DB_PORTS}
        
  rabbitmq:
    container_name: RabbitMq
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "chatConsumer"
      RABBITMQ_DEFAULT_PASS: "P@ssw0rd"
