version: '3'

services:
  
  backend:
      build: ./backend
      container_name: backend
      environment:
        - FrontendHost__Main = ${FRONT__MAIN}
        - FrontendHost__Admin = ${FRONT__ADMIN}
        - ASPNETCORE_ENVIRONMENT = ${BACK_ASP_ENV}
      ports:
        - ${BACK_ASP_PORTS}
        
  website:
      build: ./frontend/website
      container_name: frontend
      
      ports:
        - ${FRONT_WEBSITE_PORTS}
        
  admin:
      build: ./frontend/admin
      container_name: admin_dashboard
      ports:
        - ${FRONT_ADMIN_PORTS}