version: '3.9'

services:
  
  backend:
      build: ./backend
      container_name: backend
      environment:
        - FrontendHost__Main = ${FRONT__MAIN}
        - FrontendHost__Admin = ${FRONT__ADMIN}
        - ASPNETCORE_ENVIRONMENT=${BACK_ASP_ENV}
        - ASPNETCORE_URLS=${ASPNETCORE_URLS}
        - ASPNETCORE_HTTPS_PORT=${ASPNETCORE_HTTPS_PORT}
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
        - Authorization__Google__AppId = ${GOOGLE_APP_ID}
        - Authorization__Google__AppSecret = ${GOOGLE_APP_SECRET}
      depends_on:
       - db    
      ports:
        - ${BACK_ASP_PORTS}
        - ${BACK_ASP_PORTS2}
      volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        
  website:
      build: ./frontend/website
      container_name: frontend
      environment:
        - REACT_APP_WEBSITE_API_URL=${WEBSITE_API_URL}
        - REACT_APP_WEBSITE_CHAT_URL=${WEBSITE_CHAT_URL}
      ports:
        - ${FRONT_WEBSITE_PORTS}
        
  admin:
      build: ./frontend/admin
      container_name: admin_dashboard
      environment:
        - REACT_APP_ADMIN_API_URL=${ADMIN_API_URL}
      ports:
        - ${FRONT_ADMIN_PORTS}
  db:
      container_name: database
      image: postgres:latest
      environment:
        POSTGRES_DB: Carsharing
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ../2. Init Database:/docker-entrypoint-initdb.d
        - habrdb-data:/var/lib/postgresql/data
      ports:
        - ${DB_PORTS}
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_EMAIL: "goust334@gmail.com"
      PGADMIN_PASSWORD: "P@ssw0rd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORTS}

volumes:
  habrdb-data:
  pgadmin-data: