version: "3"
services:
  rabbitmq:
    container_name: RabbitMq
    image: "rabbitmq:3-management"
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    
