apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: frontend
          image: valentine1907/admin_website:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env: 
            - name : REACT_APP_ADMIN_API_URL
              value: https://localhost:8080/api/
            - name: REACT_APP_WEBSITE_API_URL
              value: https://localhost:8080/api
            - name : REACT_APP_WEBSITE_CHAT_URL
              value: https://localhost:8080/chat
            - name:  REACT_LOCAL_HOST
              value: http://localhost:3001

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer