apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        env: prod
        app: backend
    spec:
      containers:
        - name: backend
          image: valentine1907/carsharing_backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: http-web-api
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development          
          - name: KnownHosts__FrontendHosts__Main
            value: http://localhost:3000
          - name: KnownHosts__FrontendHosts__Admin
            value: http://localhost:3001
          - name: KnownHosts__BackendHosts__FileService
            value: http://host.docker.internal:7125
          - name: ASPNETCORE_URLS
            value: https://+443;http://+80
          - name: ASPNETCORE_HTTPS_PORT
            value: "443"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "/https/aspnetapp.pfx"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            value: "password12345"
          - name: ConnectionStrings__DefaultConnection
            value: User ID=postgres;Password=P@ssw0rd;Host=postgres-service;Port=5432;Database=Carsharing;
          - name: Authorization__Google__AppId
            value: "687415070028-3o7siun1s5skobj4bao912tebcjbp34f.apps.googleusercontent.com"
          - name: Authorization__Google__AppSecret
            value: "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"
          - name: RabbitMqConfig__Username
            value: chatConsumer
          - name: RabbitMqConfig__Password
            value: Passw0rd
          - name: RabbitMqConfig__Hostname
            value: rabbitmq-service
          - name: RabbitMqConfig__Port
            value: "5672"
        


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 443
  type: LoadBalancer