apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          env:
            - name: MINIO_ROOT_USER
              value: carsharing
            - name: MINIO_ROOT_PASSWORD
              value: carsharingAdmin
          args:
            - server
            - /data
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: minio-api-port
            - containerPort: 9001
              name: minio-mgmt-port
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: minio-api-port
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: minio-mgmt-port
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer
  